---
title: "Untitled"
author: "Daihao Wu"
date: "11/2/2023"
output: pdf_document
---

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(readxl)
# House ID has already been changed to House_ID and Sample ID has already been changed to Sample_ID; A null values had been refilled;
full_data = read_excel("NHS_2023_Data_October_31_UniversityofToronto_First_phase_modified_Will.xlsx", sheet = "Passive air- PUF(pgm-3)", skip = 4)
```

```{r}
library(ggplot2)

# filter to only for the houses
full_data <- full_data[c(1:33), ]

# Change the period from text to numerical data
full_data = full_data %>% mutate(Period = case_when(Period == "0 month" ~ 0, Period == "3 month" ~ 3, Period == "6 month" ~ 6, Period == "9 month" ~ 9))

ggplot(full_data, aes(x = Period, y = DEP, color = as.factor(House_ID), group = as.factor(House_ID))) +
  geom_line() +
  labs(x = "Month", y = "Concentration", color = "House ID") +
  ggtitle("Concentration versus Month for Different Homes")
```
Only houses with id 1 to 3 has a complete data for month from month 0 to 9


```{r}

data_complete_month = full_data %>% filter(House_ID == "NHAQS-001" | House_ID == "NHAQS-002" | House_ID == "NHAQS-003")

## Plot the graph of the houses with complete data
p = ggplot(data_complete_month, aes(x = Period, y = DEP, color = as.factor(House_ID), group = as.factor(House_ID))) +
  geom_line() +
  labs(x = "Month", y = "Concentration", color = "House ID") +
  ggtitle("DEP versus Month for Different Homes")

## Added the date on the 0 month
start_date_data <- data_complete_month[data_complete_month$Period == 0,]

p + geom_text(
  aes(label = `Start date (yyyy-mm-dd)`),
  data = start_date_data,
  hjust = 0,  # Adjust the horizontal position of the label
  vjust = 1,  # Adjust the vertical position of the label
  show.legend = FALSE
)
```
The start date of the houses did not seem to be a factor for the difference in the trend.


```{r}
ggplot(data_complete_month, aes(x = Period, y = DPP, color = as.factor(House_ID), group = as.factor(House_ID))) +
  geom_line() +
  labs(x = "Month", y = "Concentration", color = "House ID") +
  ggtitle("DPP versus Month for Different Homes")
```

```{r}
ggplot(data_complete_month, aes(x = Period, y = DiBP, color = as.factor(House_ID), group = as.factor(House_ID))) +
  geom_line() +
  labs(x = "Month", y = "Concentration", color = "House ID") +
  ggtitle("DiBP versus Month for Different Homes")
```


```{r}
ggplot(data_complete_month, aes(x = Period, y = DnBP, color = as.factor(House_ID), group = as.factor(House_ID))) +
  geom_line() +
  labs(x = "Month", y = "Concentration", color = "House ID") +
  ggtitle("DnBP versus Month for Different Homes")
```

