---
title: "Phase 1 imputation"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  pdf_document:
    toc: true
---

## Data Set up
```{r, echo = FALSE, message = FALSE}
# This line only installs lme4 if you haven't got it installed already

library(tidyverse)
library(dplyr)
library(readr)
library(readxl)
library(janitor)
library(ggplot2)
library(gridExtra)
library(lme4)
library(lmerTest)
library(mice)
library(mitml)
library(jomo)
library(mitools)
library(miceadds)
library(ggmice)
library(gt)
library(gtExtras)
library(broom.mixed)
library(ggpubr)
library(lmtest)
library(naniar)
set.seed(1012)
```

# Phase 1

## Data setup
```{r, echo = FALSE}
raw_data <- read_excel("NHS_2023_Data_October_31_University of Toronto_First phase.xlsx", sheet = "Passive air- PUF(pgm-3)", range = "A5:BU38")
colnames(raw_data)[which(names(raw_data) == "House ID")] <- "House_ID" #change column names
colnames(raw_data)[which(names(raw_data) == "Sample ID")] <- "Sample_ID" #change column names 

FirstPhase <- raw_data %>% 
    mutate(Period = case_when(Period == "0 month" ~ 0, 
                              Period == "3 month" ~ 3, 
                              Period == "6 month" ~ 6, 
                              Period == "9 month" ~ 9, 
                              TRUE ~ as.numeric(Period)))

PAEs<- FirstPhase[,1:15] %>% 
    complete(nesting(House_ID), Period = seq(min(Period), max(Period),3), explicit = FALSE) %>%
    group_by(House_ID)

tech_survey_data <- read_excel("20231027_Technician_Survey_Data.xlsx")
tech_survey_data <- tech_survey_data %>% 
  select(id, base_ac_yn, hrv_on_yn)

# building material 
survey_data <- read_excel("20231027_0-12_Month_Questionnaire_Data.xlsx") %>% select(id, low_VOC_home, paints_yn)
build_mat <- survey_data[1:44,] %>% 
  mutate(low_VOC_home = as.factor(low_VOC_home)) %>% 
  mutate(paints_yn = ifelse(is.na(paints_yn), 0, paints_yn))

merged_data <- merge(PAEs, tech_survey_data, by.x = 'House_ID', by.y='id') 

#head(full_data)

#Convert all number strings to numeric
merged_data$DEP <- as.numeric(merged_data$DEP)
merged_data$DPP <- as.numeric(merged_data$DPP)
merged_data$DiBP <- as.numeric(merged_data$DiBP)
merged_data$DnBP <- as.numeric(merged_data$DnBP)
merged_data$BzBP <- as.numeric(merged_data$BzBP)
merged_data$DEHP <- as.numeric(merged_data$DEHP)
merged_data$DnOP <- as.numeric(merged_data$DnOP)
merged_data$DiNP <- as.numeric(merged_data$DiNP)


```


```{r}
# log chemical concentrations 
phase_1 <- merged_data%>% 
  select(House_ID, Period, DEP, DPP, DiBP, DnBP, BzBP, DEHP, DnOP, DiNP, base_ac_yn) %>% 
  mutate(DEP = log(DEP)) %>% 
  mutate(DPP = log(DPP)) %>% 
  mutate(DiBP = log(DiBP)) %>% 
  mutate(DnBP = log(DnBP)) %>% 
  mutate(BzBP = log(BzBP)) %>% 
  mutate(DEHP = log(DEHP)) %>% 
  mutate(DnOP = log(DnOP)) %>% 
  mutate(DiNP = log(DiNP))
# merge with building material (low_VOC_homes, paints_yn)
phase_1 <- merge(phase_1,build_mat,by.x = 'House_ID', by.y='id')

log_DEP_full <- phase_1 %>% 
  select(House_ID, Period, DEP, paints_yn, low_VOC_home, base_ac_yn)
log_DPP_full <- phase_1 %>% 
  select(House_ID, Period, DPP,paints_yn, low_VOC_home, base_ac_yn)
log_DiBP_full <- phase_1 %>% 
  select(House_ID, Period, DiBP,paints_yn, low_VOC_home, base_ac_yn)
log_DnBP_full <- phase_1 %>% 
  select(House_ID, Period, DnBP,paints_yn,low_VOC_home, base_ac_yn)
log_BzBP_full <- phase_1 %>% 
  select(House_ID, Period, BzBP,paints_yn,low_VOC_home, base_ac_yn)
log_DEHP_full <- phase_1 %>% 
  select(House_ID, Period, DEHP,paints_yn,low_VOC_home, base_ac_yn)
log_DnOP_full <- phase_1 %>% 
  select(House_ID, Period, DnOP,paints_yn,low_VOC_home, base_ac_yn)
log_DiNP_full <- phase_1 %>% 
  select(House_ID, Period, DiNP, paints_yn,low_VOC_home, base_ac_yn)

# some statistics 
phase_1 %>% 
  group_by(House_ID, base_ac_yn) %>% 
  summarise() %>% 
  ggplot(aes(base_ac_yn)) + 
  geom_bar()

phase_1 %>% 
  group_by(House_ID, low_VOC_home) %>% 
  summarise() %>% 
  ggplot(aes(low_VOC_home)) +
  geom_bar()

phase_1 %>% 
  group_by(low_VOC_home) %>% 
  count

phase_1 %>% 
  ggplot(aes(x = Period, y = DEP)) +
  geom_miss_point()+
  scale_x_continuous(breaks = seq(0, 9, by = 3))+
  ggtitle("Phase 1 missing data")


phase2_9months %>% 
  ggplot(aes(x = Period, y = DEP)) +
  geom_miss_point()+
  scale_x_continuous(breaks = seq(0, 9, by = 3))+
  ggtitle("Phase 2 missing data")


phase_1 %>% 
  select(Period, DEP) %>% 
  gg_miss_fct(Period)

phase2_9months %>% 
  select(Period, DEP) %>% 
  gg_miss_case(Period, show_pct = TRUE)

```

## Imputation with period and model fitting 

### DEP 
```{r echo=TRUE}
# check convergence 
fm1 <- DEP ~ Period + (1|House_ID)
imp <- jomoImpute(data = log_DEP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1012)
#plot(imp, trace = "all")
# imputation 
lvl <- c(House_ID = 1, Period = 1, DEP =1)
imp_jomo <- jomo.lmer(DEP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DEP_full, nburn = 6000, nbetween = 1000, nimp = 10, output = 0)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
# fit models 
fit_dep <- with(data = imp_mids, lmer(DEP~Period+(1|clus)))
#fit model 
fit_dep_low <- with(data = imp_mids, lmer(DEP~Period+low_VOC_home +(1|clus)))
fit_dep_ac <- with(data = imp_mids, lmer(DEP~Period+ base_ac_yn +(1|clus)))
fit_dep_paints <- with(data = imp_mids, lmer(DEP~Period+ paints_yn +(1|clus)))
fit_dep_full <- with(data = imp_mids,
                     lmer(DEP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))
# compare models 
testModels(as.mitml.result(fit_dep_ac), as.mitml.result(fit_dep), method = "D2")
testModels(as.mitml.result(fit_dep_low), as.mitml.result(fit_dep), method = "D2")
testModels(as.mitml.result(fit_dep_paints), as.mitml.result(fit_dep), method = "D2")
# save the estimate of null model 
deptest <- testEstimates(as.mitml.result(fit_dep))

#Visualization 
dep_ggmice <- ggmice(imp_mids, aes(x=Period, y=DEP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```



### DPP
```{r}
# check convergence 
fm1 <- DPP ~ Period + (1|House_ID)
imp <- jomoImpute(data = log_DPP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1012)
#plot(imp, trace = "all") #display trace plots, ACF, and R hat 
# imputation
lvl <- c(House_ID = 1, Period = 1, DPP =1)
imp_jomo <- jomo.lmer(DPP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DPP_full, nburn = 6000, nbetween = 1000, nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
#fit models
fit_dpp <- with(data = imp_mids, lmer(DPP~Period+(1|clus)))

fit_dpp_low <- with(data = imp_mids, lmer(DPP~Period+low_VOC_home +(1|clus)))
fit_dpp_ac <- with(data = imp_mids, lmer(DPP~Period+ base_ac_yn+ (1|clus)))
fit_dpp_paints <- with(data = imp_mids, lmer(DPP~Period+ paints_yn +(1|clus)))
fit_dpp_full <- with(data = imp_mids, lmer(DPP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))
# compare models 
testModels(as.mitml.result(fit_dpp_ac), as.mitml.result(fit_dpp), method = "D2")
testModels(as.mitml.result(fit_dpp_low), as.mitml.result(fit_dpp), method = "D2")
testModels(as.mitml.result(fit_dpp_paints), as.mitml.result(fit_dpp), method = "D2")
dpptest <- testEstimates(as.mitml.result(fit_dpp))
# visualization of imputation 
dpp_ggmice <- ggmice(imp_mids, aes(x=Period, y=DPP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```
### DiBP
```{r}
# check convergence 
fm1 <- DiBP ~ Period + (1|House_ID)
imp <- jomoImpute(data = log_DiBP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1012)
#plot(imp, trace = "all") #display trace plots, ACF, and R hat 

# DiBP 
lvl <- c(House_ID = 1, Period = 1, DiBP =1)
imp_jomo <- jomo.lmer(DiBP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DiBP_full, nburn = 6000, nbetween = 1000 , nimp = 10)


imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)

#fit model 
fit_dibp <- with(data = imp_mids, lmer(DiBP~Period+(1|clus)))
fit_dibp_low <- with(data = imp_mids, lmer(DiBP~Period+low_VOC_home +(1|clus)))
fit_dibp_ac <- with(data = imp_mids, lmer(DiBP~Period+ base_ac_yn+ (1|clus)))
fit_dibp_paints <- with(data = imp_mids, lmer(DiBP~Period+ paints_yn +(1|clus)))
fit_dibp_full <- with(data = imp_mids, lmer(DiBP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))

testModels(as.mitml.result(fit_dibp_ac), as.mitml.result(fit_dibp), method = "D2")
testModels(as.mitml.result(fit_dibp_low), as.mitml.result(fit_dibp), method = "D2")
testModels(as.mitml.result(fit_dibp_paints), as.mitml.result(fit_dibp), method = "D2")
dibptest <- testEstimates(as.mitml.result(fit_dibp))


dibp_ggmice <- ggmice(imp_mids, aes(x=Period, y=DiBP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```

### DnBP
```{r}
# check convergence 
fm1 <- DnBP ~ Period + (1|House_ID)
imp <- jomoImpute(data = log_DnBP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1012)
plot(imp, trace = "all") #display trace plots, ACF, and R hat 



# DnBP
lvl <- c(House_ID = 1, Period = 1, DnBP =1)
imp_jomo <- jomo.lmer(DnBP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DnBP_full, nburn = 6000, nbetween = 600, nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
#fit model 
fit_dnbp <- with(data = imp_mids, lmer(DnBP~Period+(1|clus)))
fit_dnbp_low <- with(data = imp_mids, lmer(DnBP~Period+low_VOC_home +(1|clus)))
fit_dnbp_ac <- with(data = imp_mids, lmer(DnBP~Period+ base_ac_yn+ (1|clus)))
fit_dnbp_paints <- with(data = imp_mids, lmer(DnBP~Period+ paints_yn +(1|clus)))
fit_dnbp_full <- with(data = imp_mids, lmer(DnBP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))

testModels(as.mitml.result(fit_dnbp_ac), as.mitml.result(fit_dnbp), method = "D2")
testModels(as.mitml.result(fit_dnbp_low), as.mitml.result(fit_dnbp), method = "D2")
testModels(as.mitml.result(fit_dnbp_paints), as.mitml.result(fit_dnbp), method = "D2")
dnbptest <- testEstimates(as.mitml.result(fit_dnbp))


dnbp_ggmice <- ggmice(imp_mids, aes(x=Period, y=DnBP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```
### BzBP
```{r}
fm1 <- BzBP ~ Period + (1|House_ID)
imp <- jomoImpute(data = log_BzBP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1569)
#plot(imp, trace = "all")

# BzBP
lvl <- c(House_ID = 1, Period = 1, BzBP =1)
imp_jomo <- jomo.lmer(BzBP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_BzBP_full, nburn = 6000, nbetween = 600, nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
#fit models
fit_bzbp <- with(data = imp_mids, lmer(BzBP~ Period + (1|clus)))
fit_bzbp_low <- with(data = imp_mids, lmer(BzBP~Period+low_VOC_home +(1|clus)))
fit_bzbp_ac <- with(data = imp_mids, lmer(BzBP~Period+ base_ac_yn+ (1|clus)))
fit_bzbp_paints <- with(data = imp_mids, lmer(BzBP~Period+ paints_yn +(1|clus)))
fit_bzbp_full <- with(data = imp_mids, lmer(BzBP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))
# compare models
testModels(as.mitml.result(fit_bzbp_ac), as.mitml.result(fit_bzbp), method = "D2")
testModels(as.mitml.result(fit_bzbp_low), as.mitml.result(fit_bzbp), method = "D2")
testModels(as.mitml.result(fit_bzbp_paints), as.mitml.result(fit_bzbp), method = "D2")
# save estimate of null model 
bzbptest <- testEstimates(as.mitml.result(fit_bzbp))
# visualization of imputation
bzbp_ggmice <- ggmice(imp_mids, aes(x=Period, y=BzBP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```
### DEHP
```{r}
# fm1 <- DEHP ~ Period + (1|House_ID)
# imp <- jomoImpute(data = log_DEHP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1569)
#plot(imp, trace = "all")
# DEHP
lvl <- c(House_ID = 1, Period = 1, DEHP = 1)
imp_jomo <- jomo.lmer(DEHP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DEHP_full, nburn = 6000, nbetween = 600, nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
#fit model 
fit_dehp <- with(data = imp_mids, lmer(DEHP~Period+(1|clus)))
fit_dehp_low <- with(data = imp_mids, lmer(DEHP~Period+low_VOC_home +(1|clus)))
fit_dehp_ac <- with(data = imp_mids, lmer(DEHP~Period+ base_ac_yn+ (1|clus)))
fit_dehp_paints <- with(data = imp_mids, lmer(DEHP~Period+ paints_yn +(1|clus)))
fit_dehp_full <- with(data = imp_mids, lmer(DEHP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))

testModels(as.mitml.result(fit_dehp_ac), as.mitml.result(fit_dehp), method = "D2")
testModels(as.mitml.result(fit_dehp_low), as.mitml.result(fit_dehp), method = "D2")
testModels(as.mitml.result(fit_dehp_paints), as.mitml.result(fit_dehp), method = "D2")
dehptest <- testEstimates(as.mitml.result(fit_dehp))

dehp_ggmice <- ggmice(imp_mids, aes(x=Period, y=DEHP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```
### DnOP
```{r}
# fm1 <- DnOP ~ Period + (1|House_ID)
# imp <- jomoImpute(data = log_DnOP_full,formula = fm1, n.burn = 6000, n.iter =1000,m =10, seed = 1012)
# plot(imp, trace = "all")
# DnOP
lvl <- c(House_ID = 1, Period = 1, DnOP =1)
imp_jomo <- jomo.lmer(DnOP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DnOP_full, nburn = 6000, nbetween = 1000 , nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)

#fit model 
fit_dnop <- with(data = imp_mids, lmer(DnOP~Period+(1|clus)))
fit_dnop_low <- with(data = imp_mids, lmer(DnOP~Period+low_VOC_home +(1|clus)))
fit_dnop_ac <- with(data = imp_mids, lmer(DnOP~Period+ base_ac_yn+ (1|clus)))
fit_dnop_paints <- with(data = imp_mids, lmer(DnOP~Period+ paints_yn +(1|clus)))
fit_dnop_full <- with(data = imp_mids, lmer(DnOP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))

testModels(as.mitml.result(fit_dnop_ac), as.mitml.result(fit_dnop), method = "D2")
testModels(as.mitml.result(fit_dnop_low), as.mitml.result(fit_dnop), method = "D2")
testModels(as.mitml.result(fit_dnop_paints), as.mitml.result(fit_dnop), method = "D2")
dnoptest <- testEstimates(as.mitml.result(fit_dnop))


dnop_ggmice <- ggmice(imp_mids, aes(x=Period, y=DnOP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```
### DiNP

```{r}
# fm1 <- DiNP ~ Period + (1|House_ID)
# imp <- jomoImpute(data = log_DiNP_full,formula = fm1, n.burn = 6000, n.iter = 1000,m =10, seed = 1569)
# plot(imp, trace = "all")
# DiNP
lvl <- c(House_ID = 1, Period = 1, DiNP =1)
imp_jomo <- jomo.lmer(DiNP ~ Period + (1|House_ID),
                      level = lvl, meth = "common",
                      data = log_DiNP_full, nburn = 6000, nbetween = 1000, nimp = 10)

imp_mids <- datalist2mids(#             make mids variable
  split(imp_jomo, imp_jomo$Imputation)[-1] # split and remove first element
)
#fit model 
fit_dinp <- with(data = imp_mids, lmer(DiNP~Period+(1|clus)))
fit_dinp_low <- with(data = imp_mids, lmer(DiNP~Period+low_VOC_home +(1|clus)))
fit_dinp_ac <- with(data = imp_mids, lmer(DiNP~Period+ base_ac_yn+ (1|clus)))
fit_dinp_paints <- with(data = imp_mids, lmer(DiNP~Period+ paints_yn +(1|clus)))
fit_dinp_full <- with(data = imp_mids, lmer(DiNP~Period+ paints_yn+low_VOC_home+base_ac_yn +(1|clus)))

testModels(as.mitml.result(fit_dinp_ac), as.mitml.result(fit_dinp), method = "D2")
testModels(as.mitml.result(fit_dinp_low), as.mitml.result(fit_dinp), method = "D2")
testModels(as.mitml.result(fit_dinp_paints), as.mitml.result(fit_dinp), method = "D2")
dinptest <- testEstimates(as.mitml.result(fit_dinp))

#visualize 


dinp_ggmice <- ggmice(imp_mids, aes(x=Period, y=DiNP))+
  geom_point() + scale_x_continuous(breaks = seq(0, 12, by = 3))

```

## Knitting results 

```{r}
# visualization of imputed datasets
ggarrange(dep_ggmice,dpp_ggmice,dibp_ggmice,dnbp_ggmice,bzbp_ggmice,dehp_ggmice,dehp_ggmice,dnop_ggmice,dinp_ggmice,common.legend = TRUE,legend = "bottom" )
# estimate of model 
imp1<- gt(tibble(Chemicals = c("DEP","DPP","DiBP","DnBP","BzBP", "DEHP","DnOP","DiNP"),
                   Estimate = c(deptest$estimates[2],
                                dpptest$estimates[2],
                                dibptest$estimates[2],
                                dnbptest$estimates[2],
                                bzbptest$estimates[2],
                                dehptest$estimates[2],
                                dnoptest$estimates[2],
                                dinptest$estimates[2]
                                ),
                   Std.Error = c(deptest$estimates[4],
                                 dpptest$estimates[4],
                                 dibptest$estimates[4],
                                 dnbptest$estimates[4],
                                 bzbptest$estimates[4],
                                 dehptest$estimates[4],
                                 dnoptest$estimates[4],
                                 dinptest$estimates[4]
                                 ),
                   pvalue = c(deptest$estimates[10],
                              dpptest$estimates[10],
                              dibptest$estimates[10],
                              dnbptest$estimates[10],
                              bzbptest$estimates[10],
                              dehptest$estimates[10],
                              dnoptest$estimates[10], 
                              dinptest$estimates[10]
                              ))) 
imp1 <- imp1 %>% 
  tab_header(title = "Model results of phase1 imputed data", subtitle = "Period estimates") %>% 
   gt_highlight_rows(
    rows = pvalue <= 0.05,# a logic statement
    fill = "grey",
    bold_target_only = TRUE,
    target_col = Chemicals
    ) %>% 
  fmt_number(decimals = 2, n_sigfig = 2) %>% 
  fmt_scientific(columns = pvalue, rows = pvalue <= 0.001)
```
